const steps = [
  ['Historical task · Before seeing the answer','Let the agent try for itself.','Given the repository snapshot, an issue-style task, and its current skill document, the agent explores the codebase and produces a candidate patch. The accepted human patch remains hidden.',['Repository snapshot + task','Current skill document','Agent’s candidate patch']],
  ['Historical task · Expert patch revealed','Learn from the difference.','The accepted human patch—the oracle—is now revealed. The agent compares it with its own attempt, identifying differences in file localisation, implementation logic, internal API usage, and coding style.',['Agent’s candidate patch','Accepted human patch','Contrastive reflection']],
  ['Repository onboarding · Carry experience forward','Keep the reusable lesson.','Reflection updates a persistent skill document: create useful patterns, revise incomplete rules, and remove entries contradicted by the expert patch. Repeat this loop across historical commits.',['Contrastive reflection','Existing skill document','Updated repository skills']],
  ['Held-out future task · Skills put to use','Contribute with context.','The agent receives a future task, its repository snapshot, and the accumulated skill document. It uses these learned patterns to explore and edit the repository. Future oracle patches are reserved for evaluation.',['Future snapshot + task','Accumulated repository skills','Skill-conditioned patch']]
];
function selectStep(index){const s=steps[index];document.querySelectorAll('[data-step]').forEach((b,i)=>{b.setAttribute('aria-selected',String(i===index));b.tabIndex=i===index?0:-1});document.getElementById('step-panel').setAttribute('aria-labelledby',`step-${index}`);['step-kicker','step-title','step-copy'].forEach((id,i)=>document.getElementById(id).textContent=s[i]);const f=document.getElementById('step-flow');f.replaceChildren();s[3].forEach((text,i)=>{if(i){const separator=document.createElement('span');separator.textContent=i===1?'+':'↓';f.append(separator)}const box=document.createElement('div');box.textContent=text;if(i===2)box.className='flow-result';f.append(box)});f.setAttribute('aria-label',s[3].join(', '))}
document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>selectStep(Number(b.dataset.step))));
const models=['Kimi K2.5','Claude Sonnet 4.6','Claude Opus 4.6'];
const datasets={swe:{title:'Test pass rate on 50 sampled tasks',note:'SWE-bench Pro subset · 50 stratified tasks · 4 independent rollouts. Bars show mean pass@1 (the proportion of tasks solved in one attempt), on a 0–100% scale.',metric:'Pass@1 is reported as mean ± one standard deviation over four rollouts. File IoU measures overlap with the expert’s edited files (higher is better); Line Dev measures relative patch-size deviation (lower is better). These results describe the sampled subset, not the full SWE-bench Pro leaderboard.',head:['Model / configuration','Pass@1','File IoU ↑','Line Dev ↓'],values:[[31,34],[34,40],[48,56]],rows:[['31.0 ± 2.6%','53.2%','0.54'],['34.0 ± 2.8%','58.4%','0.49'],['34.0 ± 2.3%','55.4%','0.51'],['40.0 ± 3.3%','61.5%','0.47'],['48.0 ± 2.8%','58.1%','0.47'],['56.0 ± 1.6%','65.5%','0.44']]},organic:{title:'File localisation on held-out commits',note:'Learning to Commit benchmark · 5 repositories · 10 held-out commits per repository. Bars show File IoU (overlap with the expert’s edited files), on a 0–100% scale.',metric:'All skill runs use supervised contrastive reflection with sequential learning and one shared skill document per repository (seq-all). Pairwise scores compare with the matched no-skill baseline using a model judge; they are not human acceptance rates. File IoU and Line Dev are diagnostics, not correctness measures.',head:['Model / configuration','File IoU ↑','Line Dev ↓','Pairwise ↑'],values:[[53,60],[58,65],[62,67]],rows:[['53%','0.65','—'],['60%','0.50','55%'],['58%','0.61','—'],['65%','0.46','57%'],['62%','0.58','—'],['67%','0.43','59%']]}};
function selectResults(key){const d=datasets[key];document.querySelectorAll('[data-result]').forEach(b=>{const selected=b.dataset.result===key;b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1});document.getElementById('results-panel').setAttribute('aria-labelledby',`tab-${key}`);document.getElementById('chart-title').textContent=d.title;document.getElementById('chart-note').textContent=d.note;document.getElementById('metric-note').textContent=d.metric;document.getElementById('table-caption').textContent=key==='swe'?'SWE-bench Pro subset results':'Learning to Commit benchmark results';document.getElementById('bars').innerHTML=models.map((m,i)=>`<div><div class="bar-model">${m}</div><div class="bar-pair">${d.values[i].map((v,j)=>`<div class="bar-row" aria-label="${j?'With':'Without'} skill: ${v}%"><div class="bar-track" aria-hidden="true"><div class="bar-fill ${j?'skill':''}" style="width:${v}%"></div></div><span>${v}%</span></div>`).join('')}</div><p class="bar-delta">+${d.values[i][1]-d.values[i][0]} percentage points</p></div>`).join('');document.getElementById('result-head').innerHTML='<tr>'+d.head.map(h=>`<th scope="col">${h}</th>`).join('')+'</tr>';document.getElementById('result-body').innerHTML=d.rows.map((row,i)=>`<tr class="${i%2?'skill-row':''}"><td>${models[Math.floor(i/2)]} · ${i%2?'With skill':'Without skill'}</td>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}
document.querySelectorAll('[data-result]').forEach(b=>b.addEventListener('click',()=>selectResults(b.dataset.result)));
document.querySelectorAll('[role=tablist]').forEach(list=>list.addEventListener('keydown',e=>{const tabs=[...list.querySelectorAll('[role=tab]')];let i=tabs.indexOf(document.activeElement);if(i<0)return;if(e.key==='ArrowRight')i=(i+1)%tabs.length;else if(e.key==='ArrowLeft')i=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=tabs.length-1;else return;e.preventDefault();tabs[i].focus();tabs[i].click()}));
document.getElementById('copy-citation').addEventListener('click',async()=>{const b=document.getElementById('copy-citation');try{await navigator.clipboard.writeText(document.getElementById('bibtex').textContent);b.textContent='Copied';document.getElementById('copy-status').textContent='Citation copied to clipboard.';setTimeout(()=>b.textContent='Copy citation',2000)}catch{const range=document.createRange();range.selectNodeContents(document.getElementById('bibtex'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);document.getElementById('copy-status').textContent='Citation selected. Press Control+C or Command+C to copy.';b.textContent='Text selected'}});
selectResults('swe');
